name: InTheBack
version: ${project.version}
main: com.example.MinecraftBackpackPlugin
api-version: 1.20
description: A Paper plugin that adds craftable backpack functionality to Minecraft
author: Martin Etchebarne
